vim.cmd('highlight TelescopeNormal guibg=#1f2529')
vim.cmd('highlight Floaterm guibg=#1f2529')
vim.cmd('highlight FloatermBorder guibg=#1f2529')
vim.cmd('highlight TelescopeBorder guibg=#1f2529')
vim.cmd('highlight TelescopeSelectionCaret guibg=#1f2529')
vim.cmd('highlight TelescopeMatching guibg=#1f2529')
vim.cmd('highlight TelescopePromptNormal guibg=#1f2529')
vim.cmd('highlight TelescopePromptTitle guibg=#1f2529')
vim.cmd('highlight TelescopePromptPrefix guibg=#1f2529')
vim.cmd('highlight TelescopePromptBorder guibg=#1f2529')
vim.cmd('highlight TelescopePreviewTitle guibg=#1f2529')
vim.cmd('highlight TelescopePreviewBorder guibg=#1f2529')
vim.cmd('highlight TelescopeResultsTitle guibg=#1f2529')
vim.cmd('highlight TelescopeResultsBorder guibg=#1f2529')
vim.cmd('highlight TelescopeSelection guibg=#1f2529')
vim.cmd('highlight TreesitterContext guibg=none guifg=#E67E80')
vim.cmd('highlight TreesitterContextLineNumber guibg=#E67E80 guifg=#2D353B')

-- hi TreesitterContextBottom gui=underline guisp=Grey

-- hover highlights
local bg_color = '#1f2529'

vim.cmd('highlight NormalFloat guibg=' .. bg_color)
vim.cmd('highlight FloatBorder guibg=' .. bg_color)
vim.cmd('highlight Pmenu guibg=' .. bg_color)
vim.cmd('highlight PmenuSel guibg=#D8DEE9')
vim.cmd('highlight NormalFloat guibg=' .. bg_color)
vim.cmd('highlight FloatBorder guibg=' .. bg_color)
vim.cmd('highlight PmenuThumb guibg=' .. bg_color)
vim.cmd('highlight PmenuSbar guibg=' .. bg_color)
vim.cmd('highlight PmenuThumb guibg=' .. bg_color)
vim.cmd('highlight NormalFloat guibg=' .. bg_color)
vim.cmd('highlight FloatBorder guibg=' .. bg_color)
vim.cmd('highlight TabLine guibg=#2D353B')
vim.cmd('highlight TabLineFill guibg=#2D353B')
vim.cmd('highlight TabLineSel guibg=#2D353B guifg=#A7C080')
vim.cmd('highlight StatusLine guibg=#2d353b guifg=#A7C080')
vim.cmd('highlight StatusLineNC guibg=#2f353a guifg=#D3C6AA')
