vim.g.mapleader = " "
vim.opt.ts = 4
vim.opt.sw = 4
vim.opt.shiftwidth = 4
vim.opt.tabstop = 4
vim.opt.softtabstop= 4
vim.cmd[[ set background=dark ]]
vim.opt.list = true
vim.opt.laststatus = 2
vim.opt.belloff = 'all'
vim.opt.smartindent = true
vim.opt.autoindent = true
vim.opt.number = true
vim.opt.wrap = false
vim.opt.backup = false
vim.opt.undodir = os.getenv("HOME") .. "/.vim/undodir"
vim.opt.undofile = true
vim.opt.incsearch = true
vim.opt.relativenumber = true
vim.opt.cursorline = false
vim.opt.mouse = 'a'
vim.opt.expandtab = true
vim.opt.hlsearch = true
vim.opt.clipboard = 'unnamedplus'
vim.opt.swapfile = false
vim.opt.listchars = 'tab:┃ ,eol:↴'
vim.opt.fillchars = 'eob:·'
vim.g.qf_buflist_split_lines = 1
vim.opt.efm:append("%f|%l|%m %\\|%f|\\|%l|\\|%m %m")
vim.opt.scrolloff = 10
